import { Metadata } from "next";

export const metadata: Metadata = {
    title: "About page from steam_app",
    description: "Generated by create next app",
  };
  

export default function About() {
    return <div>Select subitem</div>
}